# Generated by Django 4.2.1 on 2023-05-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=20, verbose_name="닉네임"),
        ),
    ]
